// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// @island post-panel endpoint=/api/panel/{tab} method=GET render=/static/panel.js trigger=click
func TabsDemo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"tabs-demo\"><div class=\"tabs\" data-tabs><button class=\"tab active\" data-island=\"post-panel\" data-trigger=\"click\" data-tab=\"resumen\" data-target=\"#panel-resumen\">Resumen</button> <button class=\"tab\" data-island=\"post-panel\" data-trigger=\"click\" data-tab=\"actividad\" data-target=\"#panel-resumen\">Actividad</button> <button class=\"tab\" data-island=\"post-panel\" data-trigger=\"click\" data-tab=\"config\" data-target=\"#panel-resumen\">Configuración</button></div><div id=\"panel-resumen\" class=\"tab-panel\"><h3 class=\"panel-title\">Resumen</h3><ul class=\"panel-lines\"><li>3 posts hoy</li><li>12 likes recibidos</li><li>2 comentarios</li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
