// Code generated by templ-islands generate. DO NOT EDIT.

package main

import "github.com/SalvucciFacundo/templ-islands/islands"

// RegisterIslands registra las islas declaradas con // @island en los .templ.
func RegisterIslands(reg *islands.Registry) {
	reg.RegisterRender("chat-form", "/api/chat", "POST", "/static/chat-renderer.js", "submit", islands.WithRenderer("chat-stream"))
	reg.RegisterStream("chat-stream", "/events/chat", "/static/chat-renderer.js")
	reg.Register("follow",
		[]islands.Field{
			{
				Name:      "following",
				Op:        islands.OpToggleText,
				Selector:  "[data-mutate=follow-label]",
				TrueText:  "Following",
				FalseText: "Follow",
			},
			{
				Name:  "following",
				Op:    islands.OpClassToggle,
				Class: "following",
			},
		},
		"/api/follow/{user_id}", "POST")
	reg.Register("like",
		[]islands.Field{
			{
				Name:     "likes",
				Op:       islands.OpInc,
				Selector: "[data-mutate=likes]",
				Delta:    1,
			},
			{
				Name:      "liked",
				Op:        islands.OpToggleText,
				Selector:  "[data-mutate=label]",
				TrueText:  "Liked",
				FalseText: "Like",
			},
			{
				Name:  "liked",
				Op:    islands.OpClassToggle,
				Class: "liked",
			},
		},
		"/api/like/{post_id}", "POST")
	reg.RegisterRender("new-post", "/api/posts", "POST", "/static/post-list.js", "submit", islands.WithRenderer("post-list"))
	reg.RegisterRender("comments", "/api/comments/{post_id}", "GET", "/static/comments.js", "click")
	reg.RegisterRender("delete-comment", "/api/delete_comment/{comment_id}", "POST", "/static/comments.js", "click", islands.WithRenderer("comments"))
	reg.RegisterRender("post-list", "/api/posts", "GET", "/static/post-list.js", "input")
	reg.RegisterRender("post-more", "/api/posts", "GET", "/static/post-list.js", "intersect", islands.WithRenderer("post-list"))
	reg.RegisterRender("post-panel", "/api/panel/{tab}", "GET", "/static/panel.js", "click")
}
