// Code generated by templ-islands generate. DO NOT EDIT.

package main

import "github.com/SalvucciFacundo/templ-islands/islands"

// RegisterIslands registra las islas declaradas con // @island en los .templ.
func RegisterIslands(reg *islands.Registry) {
	reg.Register("follow",
		[]islands.Field{
			{
				Name:      "following",
				Op:        islands.OpToggleText,
				Selector:  "[data-mutate=follow-label]",
				TrueText:  "Following",
				FalseText: "Follow",
			},
			{
				Name:  "following",
				Op:    islands.OpClassToggle,
				Class: "following",
			},
		},
		"/api/follow/{user_id}", "POST")
	reg.Register("like",
		[]islands.Field{
			{
				Name:     "likes",
				Op:       islands.OpInc,
				Selector: "[data-mutate=likes]",
				Delta:    1,
			},
			{
				Name:      "liked",
				Op:        islands.OpToggleText,
				Selector:  "[data-mutate=label]",
				TrueText:  "Liked",
				FalseText: "Like",
			},
			{
				Name:  "liked",
				Op:    islands.OpClassToggle,
				Class: "liked",
			},
		},
		"/api/like/{post_id}", "POST")
	reg.RegisterRender("new-post", "/api/posts", "POST", "/static/post-list.js", "submit")
	reg.RegisterRender("post-list", "/api/posts", "GET", "/static/post-list.js", "input")
}
