package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

// opGoName maps a directive op to the islands package constant name.
func opGoName(op string) string {
	switch op {
	case "inc":
		return "OpInc"
	case "toggle-text":
		return "OpToggleText"
	case "class-toggle":
		return "OpClassToggle"
	default:
		return "OpNone"
	}
}

// OpName exposes the islands constant name to the generation template.
func (f FieldSpec) OpName() string {
	return opGoName(f.Op)
}

// generate writes out with the registry calls for the scanned islands.
func generate(out, pkg string, isles []IslandSpec) error {
	var buf bytes.Buffer
	tmpl, err := template.New("gen").Parse(genTemplate)
	if err != nil {
		return err
	}
	if err := tmpl.Execute(&buf, map[string]any{
		"Package": pkg,
		"Islands": isles,
	}); err != nil {
		return err
	}

	// gofmt la salida para que el codigo generado sea siempre identico.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formateando codigo generado: %w", err)
	}
	return os.WriteFile(out, formatted, 0o644)
}

const genTemplate = `// Code generated by templ-islands generate. DO NOT EDIT.

package {{ .Package }}

import "github.com/SalvucciFacundo/templ-islands/islands"

// RegisterIslands registra las islas declaradas con // @island en los .templ.
func RegisterIslands(reg *islands.Registry) {
{{- range .Islands }}
{{- if .Render }}
	reg.RegisterRender("{{ .Name }}", "{{ .Endpoint }}", "{{ .Render }}", "{{ .Trigger }}")
{{- else }}
	reg.Register("{{ .Name }}",
		[]islands.Field{
{{- range .Fields }}
			{
				Name: "{{ .Name }}",
				Op:   islands.{{ .OpName }},
{{- if .Selector }}
				Selector: "{{ .Selector }}",
{{- end }}
{{- if .Delta }}
				Delta: {{ .Delta }},
{{- end }}
{{- if .TrueText }}
				TrueText: "{{ .TrueText }}",
{{- end }}
{{- if .FalseText }}
				FalseText: "{{ .FalseText }}",
{{- end }}
{{- if .Class }}
				Class: "{{ .Class }}",
{{- end }}
			},
{{- end }}
		},
		"{{ .Endpoint }}", "{{ .Method }}")
{{- end }}
{{- end }}
}
`
